### PR TITLE
fix: check total protocol fee for gyro pools

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
closes https://github.com/BalancerMaxis/bal_addresses/issues/442

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
needs https://github.com/BalancerMaxis/bal_addresses/pull/450 merged first in order to test properly

**Comment by gosuto-inzasheru** [comment]
ok ran it on top of that branch, result in `core_pools.json` looks great:

Screenshot 2024-10-03 at 12 54 40

**Comment by gosuto-inzasheru** [comment]
`0x46472cba35e6800012aa9fcc7939ff07478c473e00020000000000000000056c` does get recognised as a core pool since it has collected protocol fees:
```
{
  "data": {
    "pools": [
      {
        "symbol": "ECLP-GHO-AUSDC",
        "priceRateProviders": [
          {
            "address": "0x87cd462a781c0ca843eab131bf368328848bb6fd"
          },
          {
            "address": "0x0000000000000000000000000000000000000000"
          }
        ],
        "totalLiquidity": "5524978.078679728331091983020822088",
        "protocolYieldFeeCache": null,
        "swapFee": "0.0001",
        "poolType": "GyroE",
        "poolTypeVersion": 2,
        "totalProtocolFee": "1888.157573909738882107340607911349",
        "totalProtocolFeePaidInBPT": "2184.364070426271530776"
      }
    ]
  }
}
```

**Comment by gosuto-inzasheru** [comment]
this might be due to fees previously having been in place and later set to 0. we might be able to filter out such edge cases when migrating the whole query to apiv3, for now not worth it to do so on the old core subgraph

**Review by Tritium-VLK — APPROVED** [review]

**Pull request merged**
